import { ApplicationConfig, LOCALE_ID, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';

import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import Aura from '@primeng/themes/aura';
import { providePrimeNG } from 'primeng/config';
import { routes } from './app.routes';
import { registerLocaleData } from '@angular/common';
import localePt from '@angular/common/locales/pt';
import { provideHttpClient } from '@angular/common/http';

registerLocaleData(localePt);
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(),
    provideAnimationsAsync(),
    providePrimeNG({
      translation: {
        startsWith: 'Começa com',
        contains: 'Contém',
        notContains: 'Não contém',
        endsWith: 'Termina com',
        equals: 'Igual',
        notEquals: 'Diferente',
        noFilter: 'Sem Filtro',
        lt: 'Menor que',
        lte: 'Menor ou igual a',
        gt: 'Maior que',
        gte: 'Maior ou igual a',
        is: 'É',
        isNot: 'Não é',
        before: 'Antes de',
        after: 'Depois de',
        dateIs: 'Data é',
        dateIsNot: 'Data não é',
        dateBefore: 'Data antes de',
        dateAfter: 'Data depois de',
        clear: 'Limpar',
        apply: 'Aplicar',
        matchAll: 'Corresponder Todos',
        matchAny: 'Corresponder Qualquer',
        addRule: 'Adicionar Regra',
        removeRule: 'Remover Regra',
        accept: 'Sim',
        reject: 'Não',
        choose: 'Escolher',
        upload: 'Enviar',
        cancel: 'Cancelar',
        fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
        dayNames: ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado'],
        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        monthNames: [
          'Janeiro',
          'Fevereiro',
          'Março',
          'Abril',
          'Maio',
          'Junho',
          'Julho',
          'Agosto',
          'Setembro',
          'Outubro',
          'Novembro',
          'Dezembro',
        ],
        monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        dateFormat: 'dd/mm/yy',
        firstDayOfWeek: 0,
        today: 'Hoje',
        weekHeader: 'Sem',
        weak: 'Fraco',
        medium: 'Médio',
        strong: 'Forte',
        passwordPrompt: 'Digite uma senha',
        emptyMessage: 'Nenhuma opção disponível',
        emptyFilterMessage: 'Nenhum resultado encontrado',
        fileChosenMessage: '{0} arquivos',
        noFileChosenMessage: 'Nenhum arquivo escolhido',
        pending: 'Pendente',
        chooseYear: 'Escolher Ano',
        chooseMonth: 'Escolher Mês',
        chooseDate: 'Escolher Data',
        prevDecade: 'Década Anterior',
        nextDecade: 'Próxima Década',
        prevYear: 'Ano Anterior',
        nextYear: 'Próximo Ano',
        prevMonth: 'Mês Anterior',
        nextMonth: 'Próximo Mês',
        prevHour: 'Hora Anterior',
        nextHour: 'Próxima Hora',
        prevMinute: 'Minuto Anterior',
        nextMinute: 'Próximo Minuto',
        prevSecond: 'Segundo Anterior',
        nextSecond: 'Próximo Segundo',
        am: 'AM',
        pm: 'PM',
        searchMessage: 'Existem {0} resultados disponíveis',
        selectionMessage: '{0} itens selecionados',
        emptySelectionMessage: 'Nenhum item selecionado',
        emptySearchMessage: 'Nenhum resultado encontrado',
        aria: {
          cancelEdit: 'Cancelar Edição',
          close: 'Fechar',
          collapseRow: 'Recolher Linha',
          editRow: 'Editar Linha',
          expandRow: 'Expandir Linha',
          falseLabel: 'Falso',
          filterConstraint: 'Restrição de Filtro',
          filterOperator: 'Operador de Filtro',
          firstPageLabel: 'Primeira Página',
          gridView: 'Visualização de Grade',
          hideFilterMenu: 'Esconder Menu de Filtro',
          jumpToPageDropdownLabel: 'Ir para a Página',
          jumpToPageInputLabel: 'Ir para a Página',
          lastPageLabel: 'Última Página',
          listLabel: 'Lista de opções',
          listView: 'Visualização de Lista',
          moveAllToSource: 'Mover Todos para a Origem',
          moveAllToTarget: 'Mover Todos para o Destino',
          moveBottom: 'Mover para o Final',
          moveDown: 'Mover para Baixo',
          moveTop: 'Mover para o Topo',
          moveToSource: 'Mover para a Origem',
          moveToTarget: 'Mover para o Destino',
          moveUp: 'Mover para Cima',
          navigation: 'Navegação',
          next: 'Próximo',
          nextPageLabel: 'Próxima Página',
          nullLabel: 'Não Selecionado',
          pageLabel: 'Página {page}',
          previous: 'Anterior',
          prevPageLabel: 'Página Anterior',
          removeLabel: 'Remover',
          rotateLeft: 'Rotacionar para a Esquerda',
          rotateRight: 'Rotacionar para a Direita',
          rowsPerPageLabel: 'Linhas por página',
          previousPageLabel: 'Página Anterior',
          saveEdit: 'Salvar Edição',
          scrollTop: 'Rolar para o Topo',
          selectAll: 'Todos os itens selecionados',
          selectRow: 'Linha Selecionada',
          showFilterMenu: 'Mostrar Menu de Filtro',
          slide: 'Deslizar',
          slideNumber: 'Slide {slideNumber}',
          star: '1 estrela',
          stars: '{star} estrelas',
          trueLabel: 'Verdadeiro',
          unselectAll: 'Todos os itens desmarcados',
          unselectRow: 'Linha Desmarcada',
          zoomImage: 'Ampliar Imagem',
          zoomIn: 'Ampliar',
          zoomOut: 'Reduzir',
          selectColor: 'Selecionar Cor',
          browseFiles: 'Procurar Arquivos',
          maximizeLabel: 'Maximizar',
        },
      },
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: false,
        },
      },
    }),
    { provide: LOCALE_ID, useValue: 'pt-BR' },
  ],
};
